# Generated by Django 4.2.2 on 2023-06-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NavApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_content',
            field=models.TextField(blank=True, default='', verbose_name='Основное содержание страницы'),
        ),
    ]
