# Generated by Django 4.2.2 on 2023-06-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NavApp', '0002_alter_site_site_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_content',
            field=models.TextField(blank=True, default='0', verbose_name='Основное содержание страницы'),
        ),
    ]
