# Generated by Django 4.2.2 on 2023-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер места')),
                ('side', models.CharField(max_length=5, verbose_name='Часть (верхняя или нижняя)')),
                ('place', models.CharField(max_length=7, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ('number',),
            },
        ),
    ]
