# Generated by Django 4.2.2 on 2023-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('res', models.TextField(blank=True, verbose_name='Результат')),
                ('number_A', models.FloatField(default=0, verbose_name='A')),
                ('number_B', models.FloatField(default=0, verbose_name='B')),
                ('number_C', models.FloatField(default=0, verbose_name='C')),
            ],
        ),
    ]
