# Generated by Django 4.2.2 on 2023-06-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlgorithmApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(blank=True, max_length=7, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='place',
            name='side',
            field=models.CharField(blank=True, max_length=5, verbose_name='Часть (верхняя или нижняя)'),
        ),
    ]
