# Generated by Django 4.2.2 on 2023-06-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlgorithmApp', '0002_alter_place_place_alter_place_side'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='loc',
        ),
    ]
