# Generated by Django 4.2.2 on 2023-06-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlgorithmApp', '0004_rename_loc_place_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('number__gt', 0)), name='больше 0'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('number__lte', 54)), name='меньше или равно 54'),
        ),
    ]
