# Generated by Django 4.2.2 on 2023-06-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlgorithmApp', '0005_place_больше_0_place_меньше_или_равно_54'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.IntegerField(verbose_name='Номер места'),
        ),
    ]
