# Generated by Django 4.2.2 on 2023-06-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlgorithmApp', '0006_alter_place_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер места'),
        ),
    ]
